# Generated by Django 3.0.7 on 2020-06-10 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(help_text='Марка пива', max_length=20)),
                ('color', models.CharField(help_text='Цвет пива', max_length=10)),
                ('style', models.CharField(help_text='Сорт пива', max_length=40)),
                ('strength', models.DecimalField(decimal_places=1, max_digits=3)),
                ('country', models.CharField(help_text='Страна происхождения', max_length=30)),
                ('info', models.TextField(help_text='Краткая информация')),
            ],
            options={
                'db_table': 'beer',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_text', models.TextField()),
                ('comments_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Beer.Beer')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
