# Generated by Django 3.0.7 on 2020-06-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comments_name',
            field=models.CharField(default='Unknown user', max_length=40),
        ),
    ]
