# Generated by Django 3.0.7 on 2020-06-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beer', '0002_comments_comments_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='color',
            field=models.CharField(choices=[('Светлое', 'Светлое'), ('Тёмное', 'Тёмное')], default='Светлое', help_text='Цвет пива', max_length=10),
        ),
    ]
